package com.softcomputer.gene.web.order.requisition;

public enum MediaGenerationType {
    /**
     * Automatically generated by specimen protocol.
     */
    AUTOMATICALLY("A"),
    /**
     * Manually added by the user.
     */
    MANUALLY("M"),
    /**
     * Posted from the instruments.
     */
    POSTED("P"),
    /**
     * Reflexed by the rule.
     */
    REFLEXED("R");

    private final String value;

    private MediaGenerationType(String value)
    {
        this.value = value;
    }

    public String getValue() {
        return this.value;
    }

    public static MediaGenerationType getByValue(String val)  {
        for (MediaGenerationType currentType : MediaGenerationType.values()) {
            if (val.equals(currentType.getValue())) {
                return currentType;
            }
        }
        return null;
    }
}

