swagger: "2.0"
info:
  title: Billing validator
  version: 1.0.0.0

paths:
  /is-available:
    get:
      summary: is billing available
      operationId: isAvailableBilling
      tags:
        - billing validator
      parameters:
        - name: billing
          in: query
          type: string
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            type: boolean
