swagger: "2.0"
info:
  title: Options services
  version: 1.0.0.0

paths:
  /order-entry:
    get:
      operationId: getRequisitionOptions
      responses:
        '200':
          description: successful operation
          schema:
            $ref: 'model.yaml#/definitions/RequisitionOptions'
      tags:
        - options

  /patient-maintenance:
    get:
      operationId: getPatientMaintenanceOptions
      responses:
        '200':
          description: successful operation
          schema:
            $ref: 'model.yaml#/definitions/PatientMaintenanceOptions'
      tags:
        - options