swagger: "2.0"
info:
  title: Orders services
  version: 1.0.0.0

paths:
  /:
    put:
      summary: Save order
      operationId: save
      parameters:
        - name: dtoOrder
          in: body
          schema:
#            $ref: 'model.yaml#/definitions/Case'
            $ref: 'model.yaml#/definitions/Modifier'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/OperationResult'
      tags:
        - orders