swagger: "2.0"
info:
  title: Search services
  version: 1.0.0.0

paths:
  /pm:
    get:
      summary: search patient data
      operationId: searchPatientData
      parameters:
        - name: search-criteria
          in: query
          type: string
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: 'model.yaml#/definitions/SingleSearchResults'
      tags:
        - search

  /ord:
    get:
      summary: search patient order data
      operationId: searchPatientOrderData
      parameters:
        - name: search-criteria
          in: query
          type: string
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: 'model.yaml#/definitions/SingleSearchResults'
      tags:
        - search

  /advanced:
    get:
      summary: search advanced patient order data
      operationId: searchAdvancedPatientData
      parameters:
        - name: lastName
          type: string
          in: query
        - name: firstName
          type: string
          in: query
        - name: dob
          type: string
          in: query
        - name: mrn
          type: string
          in: query
        - name: ssn
          type: string
          in: query
        - name: chartNumber
          type: string
          in: query
        - name: orderNumber
          type: string
          in: query
        - name: billingNumber
          type: string
          in: query
        - name: clientCode
          type: string
          in: query
        - name: externalPatId
          type: string
          in: query
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/PatientData'
      tags:
        - search


