swagger: "2.0"
info:
  title: Setup services
  version: 1.0.0.0

paths:
  /clinics:
    get:
      summary: Get active clinics where any part of code or name corresponds to the given free text criteria
      operationId: getClinics
      parameters:
        - $ref: 'commons.yaml#/parameters/value'
        - name: code
          in: query
          description: clinic code
          type: string
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items: 
              $ref: 'model.yaml#/definitions/Clinic'
      tags:
        - setup

  /patient-clients:
    get:
      summary: Get extramural or outreach clinics witch suit search criteria
      operationId: getPatientClients
      parameters:
        - name: "value"
          in: query
          description: clinic code/name search criteria
          type: string
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/Clinic'
      tags:
        - setup

  /visit-clinics:
    get:
      summary: Get clinics by att doc and code/name criteria, if doc is not set - returns all clinics by code/name
      operationId: getClinicsAvailableForVisit
      parameters:
        - name: value
          in: query
          description: clinic code/name search criteria
          type: string
        - name: attDoc
          in: query
          description: attending doctor code to narrow clinic choice
          type: string
        - name: patientClient
          in: query
          description: extramural or outreach clinic set on patient
          type: string
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/Clinic'
      tags:
        - setup

  /physicians:
    get:
      summary: Get active physicians where any part of code or name corresponds to the given free text criteria
      operationId: getPhysicians
      parameters:
        - $ref: 'commons.yaml#/parameters/value'
        - name: code
          in: query
          description: code
          type: string
        - name: clinic
          in: query
          description: clinic code to filter attending doctors, full match
          type: string
        - name: role
          in: query
          description: doctor role code, full match
          type: string
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/PhysicianSetup'
      tags:
        - setup

  /diagnoses:
    get:
      summary: Get active diagnoses where any part of code or name corresponds to the given free text criteria
      operationId: getDiagnoses
      parameters:
        - $ref: 'commons.yaml#/parameters/value'
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/Diagnosis'
      tags:
        - setup

  /insurancecarriers:
    get:
      summary: Get a list of InsuranceCarrierInfo objects that have only 'code' and 'name' fields.
      operationId: getInsurances
      parameters:
        - name: code_or_name
          description: free text criteria. It is a part of Insurance Carrier code or name.
          in: query
          type: string
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/InsuranceCarrierInfo'
      tags:
        - setup

  /testdefinitions:
    get:
      summary: Get active testDefinitions where any part of ID or name corresponds to the given free text criteria
      operationId: getTestDefinitions
      parameters:
        - $ref: 'commons.yaml#/parameters/value'
        - name: testTypes
          description: types of tests for filtering
          in: query
          type: array
          items:
            type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/TestDefinitionSetup'
      tags:
        - setup

  /indications:
    get:
      summary: Get active indications
      operationId: getIndications
      parameters:
        - $ref: 'commons.yaml#/parameters/value'
        - name: primary
          in: query
          type: boolean
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/IndicationSetup'
      tags:
        - setup

  /priorities:
    get:
      summary: Get active priorities
      operationId: getPriorities
      parameters:
        - $ref: 'commons.yaml#/parameters/value'
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/Priority'
      tags:
        - setup

  /body-sites:
    get:
      summary: Get bodysites
      operationId: getBodySites
      parameters:
        - $ref: 'commons.yaml#/parameters/value'
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/BodySite'
      tags:
        - setup

  /specimens:
    get:
      summary: Get a list of specimens where any part of code or name corresponds to the given value
      operationId: getSpecimens
      parameters:
        - $ref: 'commons.yaml#/parameters/value'
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/SetupSpecimen'
      tags:
        - setup

  /reasons:
    get:
      summary: Get correspond reasons for categories. If category is empty return all reasons
      operationId: getReasons
      parameters:
        - name: categories
          description: choice codes, can be empty
          in: query
          type: array
          items:
            type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/Reason'
      tags:
        - setup

  /test-sources:
    get:
      summary: Get a list of test code versions with preferable, acceptable specimens and tubes.
      operationId: getTestSources
      parameters:
        - name: test-code-versions
          description: test code versions
          in: query
          type: array
          items:
            type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/TestSources'
      tags:
        - setup

  /micro-medias:
    get:
      operationId: getGetMicroMedias
      parameters:
        - name: code_or_name
          description: free text criteria. It is a part of Insurance Carrier code or name.
          in: query
          type: string
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/MicroMedia'
      tags:
        - setup

  /drugs:
    get:
      operationId: getDrugs
      parameters:
        - name: code_or_name
          description: free text criteria. It is a part of Drug code or name.
          in: query
          type: string
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/Drug'
      tags:
        - setup

  /test-ordering-keypads:
    get:
      description: List of tests ordering keypads
      operationId: getTestOrderingKeypad
      parameters:
        - name: dcKeypad
          description: Requisition requestng doctor keypad code
          in: query
          type: string
        - name: clKeypad
          description: Requisition clinic keypad code
          in: query
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/TestDefinitionSetup' #List<OrderingKeypad<TestDefinition>>
      tags:
        - setup

  /specimen-ordering-keypads:
    get:
      description: List of specimens ordering keypads
      operationId: getSpecimenOrderingKeypad
      parameters:
        - name: dcKeypad
          description: Requisition requestng doctor keypad code
          in: query
          type: string
        - name: clKeypad
          description: Requisition clinic keypad code
          in: query
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/SetupSpecimen' #List<OrderingKeypad<Specimen>>
      tags:
        - setup

  /call-request-recipients:
    get:
      summary: Recipients for call request
      operationId: getCallRequestRecipients
      parameters:
        - name: value
          description: free text criteria
          in: query
          type: string
          required: true
        - $ref: 'commons.yaml#/parameters/itemsCount'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/Recipient'
      tags:
        - setup

  /qualities:
    get:
      summary: List of qualities
      operationId: getQualities
      parameters:
        - name: value
          description: free text criteria
          in: query
          type: string
          required: true
        - name: type
          description: Quality type
          in: query
          type: string
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/Quality'
      tags:
        - setup

  /bodysite-result-keypad:
    get:
      summary: bodySite result ResulKeypad
      operationId: getBodySiteKeypad
      parameters:
        - name: specType
          description: specimen type, can be empty
          in: query
          type: string
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: 'model.yaml#/definitions/ResulKeypad'
      tags:
        - setup

  /insurance-group:
    get:
      summary: active insurance groups
      operationId: getInsuranceGroups
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/InsuranceGroup'
      tags:
        - setup


