swagger: "2.0"
info:
  title: User defined field setup services
  version: 1.0.0.0

paths:
  /:
    get:
      summary: read testLevel user defined field
      operationId: readUserDefinedFieldSetupByTest
      tags:
        - user defined field setup
      parameters:
        - name: testCodeVersions
          in: query
          required: true
          type: array
          items:
            type: string
        - name: promptTypes
          in: query
          required: true
          type: array
          items:
            type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/UserDefinedFieldSetup'
