swagger: "2.0"
info:
  title: User defined field services
  version: 1.0.0.0

paths:
  /test-level:
    get:
      summary: read testLevel user defined field
      operationId: readTestLevelUserDefinedField
      tags:
        - user defined field
      parameters:
        - name: testCodeVersions
          in: query
          required: true
          type: array
          items:
            type: string
        - name: promptTypes
          in: query
          required: true
          type: array
          items:
            type: string
        - name: ownerId
          in: query
          required: false
          type: integer
          format: int64
        - name: ownerType
          in: query
          required: false
          type: string
#          enum: 'model.yaml#/definitions/UserDefinedFieldOwnerType'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: 'model.yaml#/definitions/UserDefinedField'
