swagger: "2.0"
info:
  title: Visits service
  version: 1.0.0.0

paths:
  /{billing}/header:
    get:
      summary: Get single visit header
      operationId: getSingleVisitHeader
      tags:
        - visit
      parameters:
        - name: billing
          in: path
          type: string
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: 'model.yaml#/definitions/VisitHeader'

  /{billing}/merge:
    post:
      summary: merge visits
      operationId: mergeVisits
      tags:
        - visit
      parameters:
        - name: billing
          in: path
          type: string
          required: true
        - name: billing
          in: query
          type: string
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            type: boolean
